//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingjoyFramework.UIFramework.Runtime.Views
{
    using System;
    
    
    /// 当前文件自动生成，禁止修改
    public partial class GameHall : WingjoyFramework.UIFramework.Runtime.Views.BaseView
    {
        
        /// GameHall/WatchinAdvertising
        private UnityEngine.RectTransform m_WatchinAdvertisingRectTransform;
        
        /// GameHall/Lobby
        private UnityEngine.RectTransform m_LobbyRectTransform;
        
        /// GameHall/Store/topFrame
        private UnityEngine.UI.Image m_topFrameImage;
        
        public GameHall(UnityEngine.Transform mTransform, WingjoyFramework.UIFramework.Runtime.Enums.UIViewType mViewType) : 
                base(mTransform, mViewType)
        {
        }
        
        public UnityEngine.RectTransform WatchinAdvertisingRectTransform
        {
            get
            {
                return m_WatchinAdvertisingRectTransform;
            }
        }
        
        public UnityEngine.RectTransform LobbyRectTransform
        {
            get
            {
                return m_LobbyRectTransform;
            }
        }
        
        public UnityEngine.UI.Image topFrameImage
        {
            get
            {
                return m_topFrameImage;
            }
        }
    }
}
