//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingjoyFramework.UIFramework.Runtime.Views
{
    using System;
    using UnityEngine;
    
    
    public partial class GameHall : WingjoyFramework.UIFramework.Runtime.Views.BaseView
    {
        
        public override void Init()
        {
            base.Init();
            m_WatchinAdvertisingRectTransform = _transform.Find("WatchinAdvertising").GetComponent<UnityEngine.RectTransform>();
            m_LobbyRectTransform = _transform.Find("Lobby").GetComponent<UnityEngine.RectTransform>();
            m_topFrameImage = _transform.Find("Store/topFrame").GetComponent<UnityEngine.UI.Image>();
        }
        
        public override void OnStart()
        {
            base.OnStart();
        }
        
        public override void OnPause()
        {
            base.OnPause();
        }
        
        public override void OnResume()
        {
            base.OnResume();
        }
        
        public override void OnExit()
        {
            base.OnExit();
        }
        
        public override void OnDestroy()
        {
            base.OnDestroy();
        }
    }
}
