//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingjoyFramework.UIFramework.Runtime.Views
{
    using System;
    using UnityEngine;
    
    
    public partial class UITestForm : WingjoyFramework.UIFramework.Runtime.Views.BaseView
    {
        
        public override void Init()
        {
            base.Init();
        }
        
        public override void OnStart()
        {
            base.OnStart();
        }
        
        public override void OnPause()
        {
            base.OnPause();
        }
        
        public override void OnResume()
        {
            base.OnResume();
        }
        
        public override void OnExit()
        {
            base.OnExit();
        }
        
        public override void OnDestroy()
        {
            base.OnDestroy();
        }
    }
}
