//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingjoyFramework.UIFramework.Runtime.Views
{
    using System;
    
    
    /// 当前文件自动生成，禁止修改
    public partial class UITestForm : WingjoyFramework.UIFramework.Runtime.Views.BaseView
    {
        
        public UITestForm(UnityEngine.Transform mTransform, WingjoyFramework.UIFramework.Runtime.Enums.UIViewType mViewType) : 
                base(mTransform, mViewType)
        {
        }
    }
}
